### ISSUE TITLE
notify user to clean up 

### ISSUE THREAD

**Issue by gautamshrm3** [worker8/TourGuide#1]
Is there any method to check for tour guide is finished or clean up notification

**Comment by worker8** [comment]
There is currently **no** method to check whether TourGuide is showing or cleaned up. 

If it is implemented, it will look something like this `mTourGuideHandler.isShowing();` Do you need a method like this? Can you show a use case for it?

I will consider adding this method.

For cleaning up, you can use `mTourGuideHandler.cleanUp();`

**Comment by gautamshrm3** [comment]
yes we want
please refer the show case view here they provide us to one shot method to show tour only one time

**Comment by worker8** [comment]
I think what you need is `SharedPreference`: http://developer.android.com/guide/topics/data/data-storage.html#pref

By using SharedPreference, key-value pairs can be stored in an Android device. You can use this to set a flag to indicate whether TourGuide has already been shown or not.

**Comment by gautamshrm3** [comment]
Thanks,
But this is secondary option to handle this case.

**Comment by worker8** [comment]
Thanks for the suggestion, I will implement a method called `TourGuide.isFirstTimeUser()` and `TourGuide.setFirstTimeUser(boolean)` in the future and close this issue.

**Comment by worker8** [comment]
I added this to the todo list in the Roadmap ([check here](https://github.com/worker8/TourGuide/wiki/Roadmap#tourguide-class-itself)), so I will close this issue for now.
