### ISSUE TITLE
tooltip not pointing to correct view.

### ISSUE THREAD

**Issue by devjon** [worker8/TourGuide#10]
Hi,
I am using fragment in my activity. I am trying to create a tutorial for a fragment screen but somehow the the view being highlighted is not the correct one. I am iniating the Tourguide code in `onViewCreated` function of the fragment. Is it something I am missing considerably.

**Comment by worker8** [comment]
Can you show me an example of how you use it? It might be a bug, I need to reproduce it to be able to fix it.

**Comment by devjon** [comment]
I was iniating the the ToolTip in `onCreateView`, doing it in `view.Post()` callback solved the problem. 

Thanks!
