### ISSUE TITLE
Tooltip.xml conflicts with AppCompat after upgrading to Android 26.1.0

### ISSUE THREAD

**Issue by gawrav** [worker8/TourGuide#120]
https://stackoverflow.com/a/46014550/5984239

I guess renaming tooltip.xml to tour guide_tooltip.xml should resolve it

**Comment by AleksanderMielczarek** [comment]
I get similar error.

> Warning:android.support.v7.widget.TooltipPopup: can't find referenced field 'int message' in program class android.support.v7.appcompat.R$id
> 
> Error:Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: there were 11 duplicate class definitions.
>       (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
> Warning: android.support.v7.widget.TooltipPopup: can't find referenced field 'int message' in program class android.support.v7.appcompat.R$id
> Warning: there were 1 unresolved references to program class members.
>          Your input classes appear to be inconsistent.
>          You may need to recompile the code.
>          (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:transformClassesAndResourcesWithProguardForDebug'.
> > Job failed, see logs for details
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 49s

**Comment by ghost** [comment]
I get this error as well!

**Comment by McSullivan** [comment]
Experiencing the same problem.

**Comment by hardwinder** [comment]
We also have this kind of error 
@worker8 🔫

**Comment by joelphilippage** [comment]
It took me forever to figure out what was crashing my app. Please fix this soon.

**Comment by vikingmobile** [comment]
I also just tracked down a pretty common crash in my app due to the tooltip.xml naming conflict with the newer support library versions.  It would be nice to have a fix, like akaita's, released as soon as possible.

**Comment by vikingmobile** [comment]
For me, it appears this issue is resolved with support library version 27.1.0

**Comment by worker8** [comment]
This should be fixed by https://github.com/worker8/TourGuide/pull/130/files (version: 1.0.19-SNAPSHOT@aar)
