### ISSUE TITLE
On touch - listener for dismiss

### ISSUE THREAD

**Issue by ieronimakisp** [worker8/TourGuide#14]
Hi there, what a remarkable lib)

When the view that's inside playOn() is pressed, the tooltip, pointer and overlay dont' go away.

So, i was wondering is there any other way to touch a tooltip and dismiss it somehow so that perhaps you move to the next step of your tour guide?

**Comment by xinghengwang** [comment]
I concur with this. I want be able to dismiss the tool tip and display when user does anything else... I want to teach the user what the button does, but not force user to click on the button.

**Comment by xinghengwang** [comment]
much appreciated if there is a way to do this.

**Comment by worker8** [comment]
You can now use the `setOnClickListener()` method of the `Overlay` to do this:

```
Overlay overlay = new Overlay()
                .setBackgroundColor(Color.parseColor("#AAFF0000"))
                // Note: disable click has no effect when setOnClickListener is used, this is here for demo purpose
                // if setOnClickListener is not used, disableClick() will take effect
                .disableClick(false)
                .setStyle(Overlay.Style.Rectangle)
                .setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        mTutorialHandler.cleanUp();
                    }
                });
```

Refer to [this example](https://github.com/worker8/TourGuide/blob/master/app/src/main/java/tourguide/tourguidedemo/OverlayCustomizationActivity.java).
