### ISSUE TITLE
Showing a TourGuide with multiple view focuses

### ISSUE THREAD

**Issue by ethpran** [worker8/TourGuide#19]
While I can use this library to instantiate multiple TourGuides with Tooltips next to several different views, I can't set more than one Overlay at a time because one covers the other and makes the second unclickable. There are instances where I'd like to have a focus on several different views at a time and I currently can't do that. You would probably need to change the implementation of the Overlay to use a RelativeLayout instead of a FrameLayout, but I think it could be a nice feature. Any plans to add some kind of functionality to achieve this effect in the near future?

**Comment by worker8** [comment]
Hi ethpran,
This sounds like a good idea, but I don't think I will implement this in the near future. Sorry about it. :(
This is because there are other bugs and issues that has higher priority.

I added to the todo list: https://github.com/worker8/TourGuide/wiki/Roadmap#overlay-features
