### ISSUE TITLE
Cannot fetch dependencies

### ISSUE THREAD

**Issue by zhanhui913** [worker8/TourGuide#31]
Hi there, 
I'm trying to add this library into my app and for some reason it is not letting me add this.

Here's my app's build.gradle:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

defaultConfig {
    applicationId "com.mstar.hotmaps"
    minSdkVersion 16
    targetSdkVersion 21
    versionCode 1
    versionName "1.0"
   }
   buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }
}

dependencies {
  compile fileTree(dir: 'libs', include: ['*.jar'])
  testCompile 'junit:junit:4.12'
  compile 'com.android.support:appcompat-v7:22.2.1'
  compile 'com.google.android.gms:play-services:7.8.0'
  compile ('com.github.worker8.tourguide:1.0.13-SNAPSHOT@aar'){
      transitive=true
  }
}
```

Is there anything I'm missing?

Thanks.

**Comment by worker8** [comment]
Hi there,
What error are you having?

**Comment by zhanhui913** [comment]
HI there, the error I'm having is : 

```
  Failed to resolve: com.github.worker8:tourguide:1.0.13-SNAPSHOT:
```

**Comment by worker8** [comment]
Thanks for trying out this library. 

Did you add the snapshot url to under repositories like this?

```
repositories {
    mavenCentral()
    maven(){
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by zhanhui913** [comment]
In my build.grade for the Project :
![screen shot 2015-08-20 at 10 57 34 am](https://cloud.githubusercontent.com/assets/5704065/9391168/211e9168-472a-11e5-9909-d0be9132a1ae.png)

In my build.grade for module:

![screen shot 2015-08-20 at 10 58 07 am](https://cloud.githubusercontent.com/assets/5704065/9391179/33ed1a9e-472a-11e5-9e8f-a5328147c01d.png)

**Comment by worker8** [comment]
I believe this is because of `.tourguide` instead of `:tourguide`.

Try changing this:

```
compile ('com.github.worker8.tourguide:1.0.13-SNAPSHOT@aar'){
      transitive=true
}
```

to 

```
compile ('com.github.worker8:tourguide:1.0.13-SNAPSHOT@aar'){
      transitive=true
}
```

**Comment by zhanhui913** [comment]
Wow, thanks. 
Good eye there. 
That fixed the problem.
Cheers mate.
Now I can finally start using your library.

**Comment by 0samir0** [comment]
I have the same problem, Failed to resolve: com.github.worker8:tourguide:1.0.17-SNAPSHOT
I have in build.gradle(Module:app)
```
compile ('com.github.worker8:tourguide:1.0.17-SNAPSHOT@aar'){
        transitive=true
    } 
```
and in build.gradle(Project)
```
mavenCentral()
        maven(){
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }
```

**Comment by piyushmishhy** [comment]
Failed to resolve: com.github.worker8:tourguide:1.0.17-SNAPSHOT. Please help

Build grade from project


[build project.txt](https://github.com/worker8/TourGuide/files/452318/build.project.txt)

build grade from app
[build app.txt](https://github.com/worker8/TourGuide/files/452319/build.app.txt)

**Comment by piyushmishhy** [comment]
Failed to resolve: com.github.worker8:tourguide:1.0.17-SNAPSHOT. Please help

Build grade from project
`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'
        classpath 'com.google.gms:google-services:3.0.0'
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        mavenCentral()
        maven(){
                url "https://oss.sonatype.org/content/repositories/snapshots"
            }

```
}
```

}

task clean(type: Delete) {
    delete rootProject.buildDir
}

`

build grade from app

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"

```
defaultConfig {
    applicationId "com.example.mishhy.hd"
    minSdkVersion 16
    targetSdkVersion 24
    versionCode 1
    versionName "1.0"

}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        signingConfig signingConfigs.debug
    }
}
packagingOptions {
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/LICENSE-FIREBASE.txt'
    exclude 'META-INF/NOTICE'
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'

```
compile  'com.android.support:appcompat-v7:24.1.1'
compile 'com.android.support:recyclerview-v7:24.1.1'
compile 'com.android.support:cardview-v7:24.1.1'
compile 'com.android.support:design:24.1.1'
compile 'com.theartofdev.edmodo:android-image-cropper:2.2.+'
```

 compile ('com.github.worker8:tourguide:1.0.17-SNAPSHOT@aar'){  

```
        transitive=true
}
```

`
