### ISSUE TITLE
disableClick() method doesn't work properly

### ISSUE THREAD

**Issue by enterpredator** [worker8/TourGuide#37]
From documentation:

> **disableClick(true)** will make elements covered by the overlay to become unclickable.

But this option doesn't work with simple example:

``` java
        TourGuide.init(getActivity()).with(TourGuide.Technique.Click)
                .setOverlay(new Overlay().disableClick(true))
                .setPointer(new Pointer())
                .setToolTip(new ToolTip().setBackgroundColor(Color.parseColor("#8bc34a"))
                                .setTitle("Title")
                                .setDescription("Description")
                                .setGravity(Gravity.BOTTOM))
                .playOn(mItemView);
```

mItemView will be still clickable.

**Comment by worker8** [comment]
Thanks for reporting! This bug is introduced in a recent update. It is now fixed in the latest version: https://github.com/worker8/TourGuide/commit/e0603c23dcae22207fb01228f66e6bba44ae5b5e (v1.0.15-SNAPSHOT)
