### ISSUE TITLE
android.support.v7.widget.Toolbar comparability

### ISSUE THREAD

**Issue by Ewg777** [worker8/TourGuide#51]
TourGuide doesn't work properly when using Toolbar.
![device-2015-10-26-125646](https://cloud.githubusercontent.com/assets/4364379/10726002/1f11dbe6-7be1-11e5-81c6-2b5e16bfaf8a.png)

**Comment by pumatus** [comment]
How do you solve this problem? Trouble to give ideas - -。

**Comment by Ewg777** [comment]
@pumatus by adding some delay

**Comment by pumatus** [comment]
Can I see the specific code? Thank you。。。-  -

**Comment by pumatus** [comment]
@Ewg777 I tried, but there is no effect, a headache. . .
getActivity().getWindow().getDecorView().getViewTreeObserver().addOnGlobalLayoutListener(){...}

**Comment by Ewg777** [comment]
``` java

new Handler().postDelayed(new Runnable() {
    @Override
    public void run() {
        showcaseView = new ShowcaseView.Builder(activity)
            .setTarget(target)
...
            .build();
        }
    }, 100);
```

**Comment by Ewg777** [comment]
Oh, sorry. I've migrated to https://github.com/amlcurran/ShowcaseView

**Comment by pumatus** [comment]
thank you very much. Lol @Ewg777
