### ISSUE TITLE
more customization

### ISSUE THREAD

**Issue by eikaramba** [worker8/TourGuide#6]
i wanted to use this library, however there are a lot of things missing for a regular use case. I give you a short list, if that is okay :)
- If i enter more than a few words the tooltip expands beyond the screen borders. It shold automatically break the lines if necessary. A simple check if the screen boundaries are reached would be good.
- The overlay is not alway exactly where i want it, e.g. i have an icon and the overlay is a little bit misplaced around it. so it would be good to be able to "adjust" its position and size through some relative value like "+=3dp" (add 3dp to the size, or move it 3dp to the left)...
- Chaining of tourguides. Is this planned, how do i do it currently? e.g. i want the user first to click here, then there, and then here.
- Option to just show the tourGuide without user interaction --> Let it close itself after the user clicked SOMEHWHERE on the Screen.

BTW: Great work nevertheless, really looking forward to this library as the de facto standard for "overlay-helping-tour-guides"

**Comment by worker8** [comment]
Thanks for your feedback.

> If i enter more than a few words the tooltip expands beyond the screen borders. It shold automatically break the lines if necessary. A simple check if the screen boundaries are reached would be good.

This is a bug, I need to fix it.

> The overlay is not alway exactly where i want it, e.g. i have an icon and the overlay is a little bit misplaced around it. so it would be good to be able to "adjust" its position and size through some relative value like "+=3dp" (add 3dp to the size, or move it 3dp to the left)...

I can understand the the size being a parameter that you can set, I will add it to the to do list. But in what cases do you need to adjust the position? I thought it's best at the center like what it is now?

> Chaining of tourguides. Is this planned, how do i do it currently? e.g. i want the user first to click here, then there, and then here.

This can be done now, I added an example in the Demo app in `InSequenceActivity.java`, check it out!

> Option to just show the tourGuide without user interaction --> Let it close itself after the user clicked SOMEHWHERE on the Screen.

This is already in the [Roadmap wiki](https://github.com/worker8/TourGuide/wiki/Roadmap#overlay-features)

**Comment by eikaramba** [comment]
The position adjusting is just because sometimes you don't want it to be centered, or the automatically extracted center values are not the same as the "visually perceived" center. e.g. if a button image is 200px width but the actual icon is only on the left or so. (bad example but i guess you know what i mean)

thx for the reply and the infos

**Comment by worker8** [comment]
I think I can what you mean, I believe the use case is there, but it will not be a very common one. I will put it in the todo list (good to have).

I added some boundary checking when text in ToolTip gets too long. It will wrap itself now. This is how it looks like:
![output](https://cloud.githubusercontent.com/assets/1988156/9139673/a50f4f08-3d66-11e5-92d4-5993d742245a.png)

I will close this issue since the bug is fixed, and the rest of the suggestions have either been implemented or added to the roadmap wiki.
