### ISSUE TITLE
ChainTourGuide missing

### ISSUE THREAD

**Issue by mtrakal** [worker8/TourGuide#69]
In samples you use some: ChainTourGuide but there is no source code or implementation of it.

Same when I use dependencies: com.github.worker8:tourguide:1.0.16-SNAPSHOT@aar

**Comment by avs20** [comment]
I am also having the same error. The source code also have only TourGuide Class 

[TourGuide](https://github.com/worker8/TourGuide/blob/master/tourguide%2Fsrc%2Fmain%2Fjava%2Ftourguide%2Ftourguide%2FTourGuide.java)

**Comment by arisprung** [comment]
Me too.

**Comment by Lianghonglu** [comment]
Me Toooo

**Comment by worker8** [comment]
So sorry about this, I forgot to commit the file, it is here now: https://github.com/worker8/TourGuide/blob/master/tourguide/src/main/java/tourguide/tourguide/ChainTourGuide.java
